// Sample registrations used to build and demo the admin portal before the
// Supabase backend is wired in. The shape mirrors the registration form.

export type Status = "pending" | "approved" | "rejected";
export type Tier = "free" | "featured";
export type Payment = "paid" | "pending" | "none";

export type Registration = {
  id: string;
  uid?: string; // Supabase uuid (absent for sample data)
  company: string;
  country: string;
  website: string;
  contact: string;
  email: string;
  phone: string;
  businessType: string;
  products: string;
  manufactures: boolean;
  manufacturingCountry: string;
  interestedAfrica: boolean;
  interestedCameroon: boolean;
  africanPct: number;
  ingredients: string;
  capacity: string;
  tier: Tier;
  payment: Payment;
  status: Status;
  submittedAt: string;
};

export const SAMPLE: Registration[] = [
  {
    id: "REG-1042",
    company: "Baobab Naturals",
    country: "Cameroon",
    website: "baobabnaturals.cm",
    contact: "Amara Nkeng",
    email: "amara@baobabnaturals.cm",
    phone: "+237 6 71 20 55 10",
    businessType: "Skincare",
    products: "Shea-based body butters and cleansers",
    manufactures: true,
    manufacturingCountry: "Cameroon",
    interestedAfrica: true,
    interestedCameroon: true,
    africanPct: 90,
    ingredients: "Shea butter, baobab oil, hibiscus",
    capacity: "60,000 units / year",
    tier: "featured",
    payment: "paid",
    status: "approved",
    submittedAt: "2026-06-28",
  },
  {
    id: "REG-1043",
    company: "Sahel Botanics",
    country: "Senegal",
    website: "sahelbotanics.sn",
    contact: "Ousmane Diop",
    email: "o.diop@sahelbotanics.sn",
    phone: "+221 77 500 33 21",
    businessType: "Essential oils",
    products: "Cold-pressed baobab and moringa oils",
    manufactures: true,
    manufacturingCountry: "Senegal",
    interestedAfrica: true,
    interestedCameroon: false,
    africanPct: 100,
    ingredients: "Moringa, baobab, neem",
    capacity: "25,000 L / year",
    tier: "featured",
    payment: "pending",
    status: "pending",
    submittedAt: "2026-07-02",
  },
  {
    id: "REG-1044",
    company: "Lagos Beauty Labs",
    country: "Nigeria",
    website: "lagosbeautylabs.ng",
    contact: "Chidinma Okafor",
    email: "chidinma@lbl.ng",
    phone: "+234 803 221 7788",
    businessType: "Cosmetics",
    products: "Colour cosmetics for deep skin tones",
    manufactures: false,
    manufacturingCountry: "",
    interestedAfrica: true,
    interestedCameroon: true,
    africanPct: 40,
    ingredients: "Marula oil, cocoa butter",
    capacity: "",
    tier: "free",
    payment: "none",
    status: "pending",
    submittedAt: "2026-07-03",
  },
  {
    id: "REG-1045",
    company: "Kilimanjaro Wellness",
    country: "Tanzania",
    website: "kiliwellness.co.tz",
    contact: "Neema Mushi",
    email: "neema@kiliwellness.co.tz",
    phone: "+255 754 118 900",
    businessType: "Wellness products",
    products: "Herbal teas and wellness supplements",
    manufactures: true,
    manufacturingCountry: "Tanzania",
    interestedAfrica: true,
    interestedCameroon: false,
    africanPct: 75,
    ingredients: "Rooibos, hibiscus, ginger",
    capacity: "40,000 units / year",
    tier: "free",
    payment: "none",
    status: "approved",
    submittedAt: "2026-06-25",
  },
  {
    id: "REG-1046",
    company: "Accra Hair Co.",
    country: "Ghana",
    website: "accrahair.gh",
    contact: "Kwame Mensah",
    email: "kwame@accrahair.gh",
    phone: "+233 24 663 1200",
    businessType: "Haircare",
    products: "Natural haircare for textured hair",
    manufactures: true,
    manufacturingCountry: "Ghana",
    interestedAfrica: true,
    interestedCameroon: true,
    africanPct: 65,
    ingredients: "Shea butter, black soap, castor oil",
    capacity: "80,000 units / year",
    tier: "featured",
    payment: "paid",
    status: "pending",
    submittedAt: "2026-07-05",
  },
  {
    id: "REG-1047",
    company: "Atlas Ingredients",
    country: "Morocco",
    website: "atlasingredients.ma",
    contact: "Yasmine Alaoui",
    email: "yasmine@atlasingredients.ma",
    phone: "+212 661 44 88 22",
    businessType: "Raw material supplier",
    products: "Argan oil and prickly-pear seed oil",
    manufactures: true,
    manufacturingCountry: "Morocco",
    interestedAfrica: true,
    interestedCameroon: false,
    africanPct: 100,
    ingredients: "Argan, prickly pear, rose",
    capacity: "120,000 L / year",
    tier: "featured",
    payment: "paid",
    status: "approved",
    submittedAt: "2026-06-20",
  },
  {
    id: "REG-1048",
    company: "Nairobi Skin Studio",
    country: "Kenya",
    website: "nairobiskin.co.ke",
    contact: "Wanjiru Kamau",
    email: "wanjiru@nairobiskin.co.ke",
    phone: "+254 722 330 110",
    businessType: "Personal care",
    products: "Soaps and deodorants",
    manufactures: false,
    manufacturingCountry: "",
    interestedAfrica: true,
    interestedCameroon: true,
    africanPct: 30,
    ingredients: "Coconut oil, aloe vera",
    capacity: "",
    tier: "free",
    payment: "none",
    status: "rejected",
    submittedAt: "2026-06-30",
  },
  {
    id: "REG-1049",
    company: "Douala Contract Mfg",
    country: "Cameroon",
    website: "doualacm.cm",
    contact: "Paul Etoundi",
    email: "paul@doualacm.cm",
    phone: "+237 6 99 41 08 77",
    businessType: "Contract manufacturer",
    products: "Contract filling and blending",
    manufactures: true,
    manufacturingCountry: "Cameroon",
    interestedAfrica: true,
    interestedCameroon: true,
    africanPct: 55,
    ingredients: "Palm oil, shea, essential oils",
    capacity: "200,000 units / year",
    tier: "featured",
    payment: "pending",
    status: "pending",
    submittedAt: "2026-07-06",
  },
  {
    id: "REG-1050",
    company: "Cape Aromatics",
    country: "South Africa",
    website: "capearomatics.co.za",
    contact: "Thandiwe Dlamini",
    email: "thandiwe@capearomatics.co.za",
    phone: "+27 82 551 4477",
    businessType: "Essential oils",
    products: "Rooibos and buchu extracts",
    manufactures: true,
    manufacturingCountry: "South Africa",
    interestedAfrica: true,
    interestedCameroon: false,
    africanPct: 95,
    ingredients: "Rooibos, buchu, marula",
    capacity: "30,000 L / year",
    tier: "free",
    payment: "none",
    status: "approved",
    submittedAt: "2026-06-22",
  },
];
